### PR TITLE
Fix registeredEvents arrow function

### PR DESCRIPTION
**Pull request by antoinebigard**
convert arrow function of registeredEvents.some to vanilla function for browser compatibility. (Safari and others)

### CODE REVIEW

**Comment by jscissr** [comment]
I prefer to leave the source in ES6, input.js has even more of it. You can use a transpiler like babel, I just added a note to the readme.

**Comment by antoinebigard** [comment]
This line is never transpile that's why :)

**Comment by antoinebigard** [comment]
Even trying to modifying by keeping ES6 synthax doesn't work. 
stuff like : if (registeredEvents.some(reg => (reg.name === name || reg.bubbled === bubbled))) 
etc..

Babel doesn't see it as ES6 synthax.

**Comment by jscissr** [comment]
Did you add babel-preset-es2015?

**Comment by antoinebigard** [comment]
Sure

**Comment by jscissr** [comment]
Then maybe you somehow exclude node_modules from transpiling. Do you use webpack? can you show your config file?

**Comment by antoinebigard** [comment]
Yes it is! My bad, transpiling is ok.
 Thanks for the support :+1:

Anyway I'll stick to my fork because removing  node_modules of  excluded folder, is inflating the final file bundle too much. In my opinion, you should have a compile version from the `npm i` because you build a lib, the majority of webpack configs exclude node_modules.

Again thanks for your support

**Pull request closed without merging**
